services:
  - docker

script:
  - docker build -t $DOCKER_USERNAME/udagram-reverseproxy ./udagram-reverseproxy
  - docker tag $DOCKER_USERNAME/udagram-reverseproxy $DOCKER_USERNAME/udagram-reverseproxy:v2

  - docker build -t $DOCKER_USERNAME/udagram-api-user ./udagram-api-user
  - docker tag $DOCKER_USERNAME/udagram-api-user $DOCKER_USERNAME/udagram-api-user:v2

  - docker build -t $DOCKER_USERNAME/udagram-api-feed ./udagram-api-feed
  - docker tag $DOCKER_USERNAME/udagram-api-feed $DOCKER_USERNAME/udagram-api-feed:v2

  - docker build -t $DOCKER_USERNAME/udagram-frontend ./udagram-frontend
  - docker tag $DOCKER_USERNAME/udagram-frontend $DOCKER_USERNAME/udagram-frontend:v2

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/udagram-reverseproxy:v2
  - docker push $DOCKER_USERNAME/udagram-api-user:v2
  - docker push $DOCKER_USERNAME/udagram-api-feed:v2
  - docker push $DOCKER_USERNAME/udagram-frontend:v2
